# Generated by Django 4.2.7 on 2023-11-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinian_matrix', '0003_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
