# Generated by Django 4.2.7 on 2023-11-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinian_matrix', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
