# Generated by Django 4.2.7 on 2023-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinian_matrix', '0005_alter_matchskills_level1_alter_matchskills_level2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchskills',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='clinian_matrix.certificate'),
        ),
    ]
