# Generated by Django 4.2.7 on 2023-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinian_matrix', '0005_nurseprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
