# Generated by Django 4.2.7 on 2023-11-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinian_matrix', '0006_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
