# Generated by Django 4.2.7 on 2023-11-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinian_matrix', '0007_managerprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='clinian_matrix.certificate'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='is_jr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='is_stable',
            field=models.BooleanField(default=False),
        ),
    ]
